//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocFast {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocFast.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10/07/2008.
        /// </summary>
        internal static string Birth_Date {
            get {
                return ResourceManager.GetString("Birth_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poly Margarita.
        /// </summary>
        internal static string CACCA_Add_FN {
            get {
                return ResourceManager.GetString("CACCA_Add_FN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poly.
        /// </summary>
        internal static string CACCA_PI_FN {
            get {
                return ResourceManager.GetString("CACCA_PI_FN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loli.
        /// </summary>
        internal static string CACCA_PI_LN {
            get {
                return ResourceManager.GetString("CACCA_PI_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danilo Caramelito.
        /// </summary>
        internal static string CACDW_Add_LN {
            get {
                return ResourceManager.GetString("CACDW_Add_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinky.
        /// </summary>
        internal static string CACDW_PI_FN {
            get {
                return ResourceManager.GetString("CACDW_PI_FN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danilo.
        /// </summary>
        internal static string CACDW_PI_LN {
            get {
                return ResourceManager.GetString("CACDW_PI_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebe de Mami.
        /// </summary>
        internal static string CDAC_Add_LN {
            get {
                return ResourceManager.GetString("CDAC_Add_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papacho.
        /// </summary>
        internal static string CDAC_PI_FN {
            get {
                return ResourceManager.GetString("CDAC_PI_FN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebe.
        /// </summary>
        internal static string CDAC_PI_LN {
            get {
                return ResourceManager.GetString("CDAC_PI_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmigliorisi@totalperform.com.
        /// </summary>
        internal static string Consumer_Email {
            get {
                return ResourceManager.GetString("Consumer_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toty Migliorisi.
        /// </summary>
        internal static string DTC_Add_LN {
            get {
                return ResourceManager.GetString("DTC_Add_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thor.
        /// </summary>
        internal static string DTC_PI_FN {
            get {
                return ResourceManager.GetString("DTC_PI_FN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toty.
        /// </summary>
        internal static string DTC_PI_LN {
            get {
                return ResourceManager.GetString("DTC_PI_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Tery\Desktop\RegressionTestingAutomation.xlsx.
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Tery\Documents\Totalperformance\ePolicy\pdfs\PrivateConfidentialDocument.pdf.
        /// </summary>
        internal static string PA_Location {
            get {
                return ResourceManager.GetString("PA_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Tery\Documents\Totalperformance\ePolicy\pdfs\LincolnMoneyGuard_Sample1.pdf.
        /// </summary>
        internal static string PDF_LocationLincoln {
            get {
                return ResourceManager.GetString("PDF_LocationLincoln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Tery\Documents\Totalperformance\ePolicy\pdfs\Std Pdf\agentdocs2013.pdf.
        /// </summary>
        internal static string PDF_LocationStd {
            get {
                return ResourceManager.GetString("PDF_LocationStd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Tery\Documents\Totalperformance\ePolicy\pdfs\Std Pdf\agentdocs2013.pdf.
        /// </summary>
        internal static string PDF_LocationStdNY {
            get {
                return ResourceManager.GetString("PDF_LocationStdNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Tery\Documents\Totalperformance\ePolicy\pdfs\1iPipeline Sample Policy.pdf.
        /// </summary>
        internal static string PDF_LocationTest {
            get {
                return ResourceManager.GetString("PDF_LocationTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoneyGuard.
        /// </summary>
        internal static string PDF_TemplateLincoln {
            get {
                return ResourceManager.GetString("PDF_TemplateLincoln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Documents.
        /// </summary>
        internal static string PDF_TemplateStd {
            get {
                return ResourceManager.GetString("PDF_TemplateStd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Documents.
        /// </summary>
        internal static string PDF_TemplateStdNY {
            get {
                return ResourceManager.GetString("PDF_TemplateStdNY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPipeline Sample Policy Template.
        /// </summary>
        internal static string PDF_TemplateTest {
            get {
                return ResourceManager.GetString("PDF_TemplateTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Tery\Documents\Totalperformance\ePolicy\pdfs\1iPipelineAgentInstructions.pdf.
        /// </summary>
        internal static string PDFEsv_Location {
            get {
                return ResourceManager.GetString("PDFEsv_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPipeline Sample Agent Instructions.
        /// </summary>
        internal static string PDFEsv_Template {
            get {
                return ResourceManager.GetString("PDFEsv_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 145 Brookeivey Lane.
        /// </summary>
        internal static string PI_AddressLine1 {
            get {
                return ResourceManager.GetString("PI_AddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpharetta.
        /// </summary>
        internal static string PI_City {
            get {
                return ResourceManager.GetString("PI_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amit.
        /// </summary>
        internal static string PI_IDCheck_FN {
            get {
                return ResourceManager.GetString("PI_IDCheck_FN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patel.
        /// </summary>
        internal static string PI_IDCheck_LN {
            get {
                return ResourceManager.GetString("PI_IDCheck_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GA.
        /// </summary>
        internal static string PI_State {
            get {
                return ResourceManager.GetString("PI_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30004.
        /// </summary>
        internal static string PI_Zip {
            get {
                return ResourceManager.GetString("PI_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://policyexpartnerportal.ipipeline.com.
        /// </summary>
        internal static string Prod_Url {
            get {
                return ResourceManager.GetString("Prod_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyEXUser_A_5.
        /// </summary>
        internal static string QA_TestCarrier_CA_Agent {
            get {
                return ResourceManager.GetString("QA_TestCarrier_CA_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyEXUser_CCM_3.
        /// </summary>
        internal static string QA_TestCarrier_CCM {
            get {
                return ResourceManager.GetString("QA_TestCarrier_CCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyEXUser_CCM_5.
        /// </summary>
        internal static string QA_TestCarrier_CCM_Transfer {
            get {
                return ResourceManager.GetString("QA_TestCarrier_CCM_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyEXUser_CCMA_5.
        /// </summary>
        internal static string QA_TestCarrier_CCMA {
            get {
                return ResourceManager.GetString("QA_TestCarrier_CCMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyEXUser_A_4.
        /// </summary>
        internal static string QA_TestCarrier_CD_Agent {
            get {
                return ResourceManager.GetString("QA_TestCarrier_CD_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a_4.
        /// </summary>
        internal static string QA_TestCarrier_CD_Agent_Search_LN {
            get {
                return ResourceManager.GetString("QA_TestCarrier_CD_Agent_Search_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmigliorisi_IA3.
        /// </summary>
        internal static string QA_TestCarrier_CD_SubGA_Agent {
            get {
                return ResourceManager.GetString("QA_TestCarrier_CD_SubGA_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyEXUser_DCM_4.
        /// </summary>
        internal static string QA_TestCarrier_DCM {
            get {
                return ResourceManager.GetString("QA_TestCarrier_DCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyEXUser_DCM_5.
        /// </summary>
        internal static string QA_TestCarrier_DCM_Transfer {
            get {
                return ResourceManager.GetString("QA_TestCarrier_DCM_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyEXUser_DCMA_4.
        /// </summary>
        internal static string QA_TestCarrier_DCMA {
            get {
                return ResourceManager.GetString("QA_TestCarrier_DCMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyEXUser_A_1.
        /// </summary>
        internal static string QA_TestCarrier_DW_Agent {
            get {
                return ResourceManager.GetString("QA_TestCarrier_DW_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmigliorisi_CCM4.
        /// </summary>
        internal static string QA_Trans_CCM {
            get {
                return ResourceManager.GetString("QA_Trans_CCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://policyexpartnerportal-qa.ipipenet.com.
        /// </summary>
        internal static string QA_Url {
            get {
                return ResourceManager.GetString("QA_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://policyexpartnerportal-qa2.ipipenet.com.
        /// </summary>
        internal static string QA2_Url {
            get {
                return ResourceManager.GetString("QA2_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234.
        /// </summary>
        internal static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to migliorisi.
        /// </summary>
        internal static string SubGA_Agent_Search_LN {
            get {
                return ResourceManager.GetString("SubGA_Agent_Search_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Owner.
        /// </summary>
        internal static string Template_Add_Role {
            get {
                return ResourceManager.GetString("Template_Add_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmigliorisi_CA3.
        /// </summary>
        internal static string UAT_CA_Agent {
            get {
                return ResourceManager.GetString("UAT_CA_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tccm_21581.
        /// </summary>
        internal static string UAT_CCM {
            get {
                return ResourceManager.GetString("UAT_CCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tccm_11581.
        /// </summary>
        internal static string UAT_CCM_Transfer {
            get {
                return ResourceManager.GetString("UAT_CCM_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmigliorisi_CCMA3.
        /// </summary>
        internal static string UAT_CCMA {
            get {
                return ResourceManager.GetString("UAT_CCMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagent_cdac1581.
        /// </summary>
        internal static string UAT_CD_Agent {
            get {
                return ResourceManager.GetString("UAT_CD_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdac.
        /// </summary>
        internal static string UAT_CD_Agent_Search_LN {
            get {
                return ResourceManager.GetString("UAT_CD_Agent_Search_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string UAT_CD_SubGA_Agent {
            get {
                return ResourceManager.GetString("UAT_CD_SubGA_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tdcm_21581.
        /// </summary>
        internal static string UAT_DCM {
            get {
                return ResourceManager.GetString("UAT_DCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tdcm_11581.
        /// </summary>
        internal static string UAT_DCM_Transfer {
            get {
                return ResourceManager.GetString("UAT_DCM_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tdcma_21581.
        /// </summary>
        internal static string UAT_DCMA {
            get {
                return ResourceManager.GetString("UAT_DCMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagent_dw1581.
        /// </summary>
        internal static string UAT_DW_Agent {
            get {
                return ResourceManager.GetString("UAT_DW_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://policyexpartnerportal-uat.ipipeline.com.
        /// </summary>
        internal static string UAT_Url {
            get {
                return ResourceManager.GetString("UAT_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12345678.
        /// </summary>
        internal static string User_Pwd {
            get {
                return ResourceManager.GetString("User_Pwd", resourceCulture);
            }
        }
    }
}
